export interface CharacterTypes {
    characterName: string
    playerName: string
    characterClass: string 
    race: string
    alignment: string
    age: number
    exp: number
    lvl: number
    hp: number
    armorClass: number
    initiative: number
    speed: number
    str: number
    dex: number
    con: number
    int: number
    wis: number
    cha: number
    passivePerception: number
    background: string
    proficiencies: string[]
    skills: string[]
    feats: string[]
    equipment: string[]
    inventory: string[]
    spells: string[]
    languages: string[]
    personalityTraits: string[]
    ideals: string[]
    bonds: string[]
    flaws: string[]
    features: string[]
    attacks: string[]
    spellsKnown: string[]
}
